### ISSUE TITLE
Invalid debug registers

### ISSUE THREAD

**Issue by flobernd** [intelxed/xed#102]
Hi, is there a reason, XED checks for invalid control-registers (e.g. CR1), but not for invalid debug-registers (DR8-DR15 and maybe DR4, DR5)?

Regarding to the SDM these ones will cause #UD:
> Use of the REX.R prefix causes an invalid-opcode exception. 

and
> When the DE flag in CR4 is set, attempts to reference DR4 and DR5 result in an
undefined opcode (#UD) exception.

I guess introducing a new mode for DR4/DR5 would be overkill, but the `REX.R` thing should be easy to implement.

**Comment by markcharney** [comment]
No good reason. Just was never a priority. Not sure it is worth doing something special for CR4.DE, but obviously can if needed. I just removed the unused DR_B() and regs DR8..15. Will push with my next pile of updates, probably later this week.

**Comment by flobernd** [comment]
Thanks! I don't think it's worth tinkering with CR4.DE either. Returning BAD_REGISTER for DR8-DR15 should do the trick.
