### ISSUE TITLE
AVX2GATHER registers

### ISSUE THREAD

**Issue by flobernd** [intelxed/xed#104]
Hi there, 

I think I found one more issue. XED disassembles `C4 E2 BD 90 5C DD A2` as `vpgatherdq ymm3, qword ptr [rbp+xmm3*8-0x5e], ymm8`.

The SDM says:

> If any pair of the index, mask, or destination registers are the same, this instruction results a UD fault.

Obviously `XMM3` is not the same register as `YMM3`, but as they are sharing the lower 128-bits, this combination should #UD as well. The SDM is not very clear about this, but fter looking at the pseudo-code and the implications, I'm pretty sure the #UD condition refers to identical register-**id**s (instead of actually identical registers).

**Comment by markcharney** [comment]
another good one. thx. how are you finding all these  issues?

**Comment by flobernd** [comment]
We feed the XED decoder with some random data and compare the results with [Zydis](https://github.com/zyantific/zydis).

If only one disassembler is able to decode the instruction, I take a deeper look into what could cause the issue. We think it's only fair to report these finds back to you; improving both libraries 😄

**Comment by lyrachord** [comment]
By document, the followings are same.
VPGATHERQD/VPGATHERQQ 
VPGATHERDD/VPGATHERDQ 
VGATHERDPS/VGATHERDPD 
VGATHERQPS/VGATHERQPD

These insts use VSIB and require operand registers used cannot be overlapped.

Consider adding another flag VEM_NO_OVERLAP(better name?)  to follow the main flag UISA_VMODRM_xMM

?

**Comment by markcharney** [comment]
@flobernd aside: pretty sure you didn't mean "scatter" in the title since (a) there are no AVX scatters and (b) scatters in AVX512 do not have this constraint; index & source can the same.

**Comment by flobernd** [comment]
You are correct! I changed the title.
