### ISSUE TITLE
4FMAPS register

### ISSUE THREAD

**Issue by flobernd** [intelxed/xed#107]
Hi there,

not sure about this one as the SDM is rather vague about it, but for the `MULTISOURCE4` registers it says:

> the notation of “+3” is used to denote that the instruction accesses 4 source registers based on
that operand; sources are consecutive, start in a multiple of 4 boundary,

Does that mean the instruction #UDs / is invalid, if the register operand does not refer to a "multiple of 4"? E.g. if `ZMM31` is used as the source register.

At the moment, XED allows all possible register values `ZMM0..ZMM31`.

**Comment by markcharney** [comment]
if you look at the pseudocode for the instruction in the SDM, you’ll see the reg id is masked so that the low 2b are zeroed regardless of what the programmers specify. we didn’t want to add #UD logic for that.

**Comment by flobernd** [comment]
Totally missed that. Thanks!
