### ISSUE TITLE
Operand types for ANDPD, etc.

### ISSUE THREAD

**Issue by andreas-abel** [intelxed/xed#114]
I think the operand types for VANDPD, VANDNPD, VORPD, and VXORPD in avx-isa.txt should be f64 instead of u64.

**Comment by markcharney** [comment]
these instructions are a little unusual. they are logical ops, not floating point. so i think the elements should be integers or just bits.

**Comment by andreas-abel** [comment]
According to the instruction set reference, VANDPD returns "the bitwise logical AND of packed double-precision floating-point values."

The ANDPD, etc. instructions in xed-isa.txt actually have type pd, which corresponds to f64. Should there really be a difference between ANDPD and VANDPD?

**Comment by andreas-abel** [comment]
The VANDPD, etc. instructions in skx-isa.xed.txt also have type f64.

**Comment by markcharney** [comment]
ok. i can certainly make them consistent in XED as u64... I can ask the doc person about the SDM types but it is probably low value to change. thanks for reporting this issue!

**Comment by andreas-abel** [comment]
When I mix PAND and ANDPD instructions, I see delays, which are probably bypass delays between the SSE-INT and SSE-FP domains. I see the same delays when mixing, e.g., MULPD and PAND, but I don't see these delays when mixing MULPD and ANDPD.

So I still think ANDPD should actually be f64.

**Comment by markcharney** [comment]
I'm still thinking about this one. I'm tending to agree with you (reluctantly), but I want to get some more opinions (from my coworkers).

**Comment by markcharney** [comment]
Ok... I talked to some of the architects. Using the operand type as a basis for performance suggestions about bypassing delays is not a good idea.  While older chips do have the behavior you indicated, it varies a lot.   And I'll see if we can improve that section you mentioned from the sw opt guide.

Bottom line: my plan is to make all the "fp logicals" use unsigned types.

**Comment by lyrachord** [comment]
Good point!

XED now use the form: xtype: override //widths document

Splitting nemonics, we can get a big list of types with kinds of attributes, such sign? align?...
f.e.
```
B |   | Q
B |   | W
D | V | Q
D | V | W
D |   | PS |  
D |   | Q | E
D |   | Q | H
D |   | Q | L
DQ | 2 |   | PS
DQ | A | 32 |  
DQ | A | 64 |  
DQ | U | 8
DQ | U | 16
F | 32 | X | 2
F | 32 | X | 4

....
```

Maybe later we can do a robust form
```
bits: type-system
```
