### ISSUE TITLE
First operand of PEXT

### ISSUE THREAD

**Issue by andreas-abel** [intelxed/xed#115]
The first operand of the PEXT instruction (in hsw-bmi-vex-isa.xed.txt) should have the type REG0=VGPR32_R():**w**:d instead of REG0=VGPR32_R():**rw**:d as it is never read (according to the instruction set reference).

**Comment by markcharney** [comment]
thx. same for pdep and andn.

**Comment by markcharney** [comment]
assuming we are good here.  let me know of you find further issues. thx
