### ISSUE TITLE
Formatting: Extra space after instructions without visible operands

### ISSUE THREAD

**Issue by flobernd** [intelxed/xed#120]
Hi there,

it seems like `xed_format_context` (only tested with `XED_SYNTAX_INTEL`) appends an extra space after instructions without visible operands (e.g. `IRETD`). Is this intended behaviour?

Best regards

**Comment by markcharney** [comment]
Yes, that is true - there is an extra space in that case. I did not think anyone would mind. I can certainly remove that space in a future commit.
