### ISSUE TITLE
Operand types for CVTPS2PI

### ISSUE THREAD

**Issue by andreas-abel** [intelxed/xed#123]
CVTPS2PI should have the same operand types as CVTTPS2PI (i.e., the MMX operand should be i32, and the other operand f32).

**Comment by markcharney** [comment]
nice catch. Thx. I'll queue up a fix.

**Comment by markcharney** [comment]
@flobernd : please file that as a separate issue. I don't think I want to add that to every MMX instr. At least not at the moment.
