### ISSUE TITLE
According to the Intel manual, MWAIT doesn't overwrite EAX

### ISSUE THREAD

**Issue by 0xd4d** [intelxed/xed#142]
SDM vol 1 12.1.2 "The MONITOR and MWAIT instructions use general purpose registers on input, they do not modify the content of those registers."

This is repeated in 12.3.6: "The registers used by MONITOR and MWAIT must be initialized properly; register content is not modified by these instructions."

```
./xed-ex1 -64 0F01C9
#   TYPE               DETAILS        VIS  RW       OC2 BITS BYTES NELEM ELEMSZ   ELEMTYPE   REGCLASS
#   ====               =======        ===  ==       === ==== ===== ===== ======   ========   ========
0   REG0              REG0=EAX SUPPRESSED  RW         D   32     4     1     32        INT        GPR
1   REG1              REG1=ECX SUPPRESSED   R         D   32     4     1     32        INT        GPR
```

It also seems that the full 64 bits are used in 64-bit mode

MONITOR: #GP(0): If RCX ≠ 0
MWAIT: #GP(0): If RCX[63:1] ≠ 0.

A little bit OT, but I found a small formatting bug:

```
./xed -64 -d 6701342534125AA5
SHORT: add dword ptr [0xa55a1234], esi

./xed -64 -d 01342534125AA5
SHORT: add dword ptr [0xa55a1234], esi
```

The last example should be sign extended to 64 bits.

**Comment by markcharney** [comment]
thx.  I have a fix for the "mwait eax should be read-only" thing. Looking at sign-extending the displacement now.

**Comment by markcharney** [comment]
thx. let me know if you encounter other issues.
