### ISSUE TITLE
Decoder fails to decode a few valid AMD instructions

### ISSUE THREAD

**Issue by 0xd4d** [intelxed/xed#146]
Wrong destination register, should be xmm1 but it's xmm0
```
660F78C1A5FD
wrong:   extrq xmm0, 0xa5, 0xfd
correct: extrq xmm1, 0xa5, 0xfd
```

W1 is allowed but xed can't decode them:

```
8FE9F812C3 = llwpcb rbx
8FE9F812CB = slwpcb rbx
```

**Comment by markcharney** [comment]
AMD doc (rev 3.25) appears to have a typo in Group 17.  It says "Vo.q" for the dest where V is defined as "YMM/XMM register specified by the ModRM.reg field."   I'm gonna assume they mean "Uo.q" for the "reg,imm,imm" form.

**Comment by markcharney** [comment]
I am little concerned that 66.0f78/0 an 66.0f79 use different dest reg specifiers.

**Comment by 0xd4d** [comment]
These two instructions are a little weird, the 2nd operand is always 32-bit according to the documentation, but xed shows it as a 64-bit register:

```
8FEAC812C334125AA5 = lwpins rsi, rbx, 0xa55a1234
8FEAC812CB34125AA5 = lwpval rsi, rbx, 0xa55a1234
```

**Comment by markcharney** [comment]
thx. added this fix too
