### ISSUE TITLE
Instruction with low-level control flow

### ISSUE THREAD

**Issue by tathanhdinh** [intelxed/xed#148]
There are some `x86` instructions which containing a low-level** control flow in its semantics, for example [div](https://c9x.me/x86/html/file_module_x86_id_72.html) because its semantics is roughly as:

    if (source == 0)
       throw exception...
    else
       return rdx:rax / source

or instructions with `rep` prefix, etc. While a `mov` or a `xor` doesn't contain any control flow.

I am trying to classify instructions of `x86` ISA depending on this criteria, my starting point now is looking into Xed's API to know if there exist functions which can give such an information, but it doesn't seem having any.

Concretely for `div`, I've checked [xed_decoded_inst_conditionally_writes_registers](https://intelxed.github.io/ref-manual/group__DEC.html#gad267d2d08e002b027915248689d1defe), [xed_operand_conditional_read/write](https://intelxed.github.io/ref-manual/group__DEC.html#gad6b80021a33c772fa74a038f17343562), but all of them return false.

Many thanks for any help.

** I'm sorry for this word, I don't know the precise terminology for this case.

NB. I've asked also this question at [reverseengineering](https://reverseengineering.stackexchange.com/questions/19347/recognizing-instructions-containing-low-level-control-flows).

**Comment by tathanhdinh** [comment]
@flobernd many thanks for your comment. I think that I have expressed badly my question.

I think also that xed doesn't give full instruction semantics, but "some". In my case, I need only know that whether the instruction contains some control flow in its semantics. For instance, with some xed API (which I described above) we can get:

- `mov rax, r8`
```
operands:                       2
uses rflag:                     no
has conditional read operand:   no
has conditional write operand:  no
conditionally write register:   no
```

- `cmovb rax, r8`
```
operands:                       3
uses rflag:                     yes
has conditional read operand:   no
has conditional write operand:  yes
conditionally write register:   yes
```

so at least I know that `cmovb` should have some conditional control flow in its semantics, while `mov` has not. I tried to apply this logic for other instructions: it works for some (e.g. `rep movsb`, etc.), but fails for some, e.g. `div` (well this case may be acceptable if we consider that exception is not control flow but side effect).

**Comment by markcharney** [comment]
Hi. Generally XED has no exposure to conditions that would cause exceptions during execution of a specific encoding.  

For some instructions, mostly those defined more recently (SSE, AVX, AVX512), we defined exception "types" (really groups or sets)  in the instruction manuals as a way of codifying the kinds of exceptions that instructions could generate. (This was done predominantly to save typing and editing in the architectural specifications as the instructions were defined).  But for the older stuff, we have not gone back and tried to collect them in to named groups based on exception conditions similarity.

**Comment by tathanhdinh** [comment]
@markcharney: many thanks for the detail explain.
