### ISSUE TITLE
Missing install target

### ISSUE THREAD

**Issue by andikleen** [intelxed/xed#15]
I'm looking at adding XED support to some other open source projects.

However the building is fairly complicated because XED doesn't seem to have an install target for Linux to install it into the standard /usr/local/{include,lib64} locations (unless I'm missing something). This requires specifying the (non standard) xed kit name everywhere in the other projects, which makes it difficult to have a build environment which works on a wide range of systems.

Would it be possible to add a standard install target?

**Comment by markcharney** [comment]
I'll take a look. Good idea. Mostly I've had people bulding from the compiled "kits" ("install" target). Big question in my mind is /usr/local/include vs /usr/local/include/xed . Latter is cleaner but would be more invasive to existing users.

**Comment by markcharney** [comment]
and the lib/lib32/lib64 confusion. knob for that...

**Comment by rscohn2** [comment]
👍 for install to standard location

**Comment by markcharney** [comment]
I believe I implemented this. #18 

let me know if you find any problems.
