### ISSUE TITLE
No support for XSTORE-RNG/XSHA1/XSHA256 instructions?

### ISSUE THREAD

**Issue by keyboardsmoke** [intelxed/xed#151]
I'm getting a general decode error attempting to disassemble 

```
f3 0f a6 c8             repz xsha1
```

and

```
0f a7 c0                xstore-rng
```

https://github.com/openssl/openssl/blob/32f803d88ec3df7f95dfbf840c271f7438ce3357/engines/asm/e_padlock-x86_64.pl#L176

https://github.com/openssl/openssl/blob/32f803d88ec3df7f95dfbf840c271f7438ce3357/engines/asm/e_padlock-x86_64.pl#L159

Are these instructions too new to be supported? I haven't seen any open issues, and looking through the IFORM/ICLASS enumerations I can't find any data on these variants. IDA disassembles it as a cmpxchg, which would be fine too, but currently I'm just getting an error code.

**Comment by markcharney** [comment]
what vendor? centaur? 
doc link?

**Comment by flobernd** [comment]
Yeah, these instructions belong to the "Padlock" extension which is only available on certain VIA Centaur CPUs. IDA is definitely wrong about that `cmpxchg`.

A manual can be found here:
http://spacehopper.org/mirrors/ftp.vtbridge.org/Docs/CPU/Nano/padlock_quick_reference_V095.pdf

**Comment by markcharney** [comment]
let me know how it works in a new issue if you see problems.
