### ISSUE TITLE
Add simple "compile and install" howto to README

### ISSUE THREAD

**Issue by andikleen** [intelxed/xed#16]
The build documentation is right now fairly complicated.

It would be good if there was a simple paragraph in the main README that describes how to build and install.

**Comment by markcharney** [comment]
How about something like this:

```
git clone https://github.com/intelxed/xed.git xed
git clone https://github.com/intelxed/mbuild.git mbuild
./mfile.py
```

and get your libxed.a from the obj directory.
Add --shared if you want a shared object build.
Ad "install" if you want the headers & libraries put in to a kit in the "kits" directory.
add "C:/python27/python " before "./mfile.py" if on windows.

Robert is suggesting I have mbuild pip-install mbuild locally to save a step and also put mbuild on pypi.

**Comment by andikleen** [comment]
Don't you need to cd into some directory for the mfile.py ?

**Comment by markcharney** [comment]
yeah... I added that as an edit after i sent the first comment.

**Comment by andikleen** [comment]
Ok looks good then.

**Comment by markcharney** [comment]
done. thx.
