### ISSUE TITLE
Inconsistent oc2 codes for FMA4 instructions

### ISSUE THREAD

**Issue by andreas-abel** [intelxed/xed#168]
All operands of the VFMADDSS instruction are 32-bit single-precision floating-point numbers. Therefore, I think their oc2 codes should all be "d". Currently, only the memory operands and the registers at the positions of possible memory operands have the "d" code, while the other registers have the "dq" code.

This is also the case for several other FMA4 instructions.

**Comment by markcharney** [comment]
So, it took me some remembering but I think I sorted this out.  Unlike "normal vex scalars", these don't copy one operand to the dest reg for bits 127:32 (ss) or 127:64 (sd).  So I made all the non-dest operands element-sized.
