### ISSUE TITLE
VIA PadLock 'montmul' instruction is missing

### ISSUE THREAD

**Issue by 0xd4d** [intelxed/xed#171]
Old issue: https://github.com/intelxed/xed/issues/151

montmul = 0F A6 C0

Documentation: http://linux.via.com.tw/support/beginDownload.action?eleid=181&fid=261

**Comment by markcharney** [comment]
How big is the memop? 4+(2*(4+8))=28 or (4+4*(4+8))=52 bytes depending on the 16/32b mode? Or is the scratch stuff ignored?

**Comment by 0xd4d** [comment]
I don't know but my guess is that each pointer is the same as the effective address size.

**Comment by markcharney** [comment]
OK... I think it is 4+ 5*asz (where asz=2 or 4 bytes)... so 14 or 24 bytes
