### ISSUE TITLE
Decoding & Re-Encoding 0xC3

### ISSUE THREAD

**Issue by D34Dspy** [intelxed/xed#182]
Hello there,

I have experienced a problem, when I try to decode and encode the instruction "pop ebp" (0xC3).
It is working fine, when I decode it, however on encoding, it outputs the byte 0x93 ("xchg ebx,eax").
Is that supposed to be like that?

Here is my testing code: https://pastebin.com/PGAABZCw
*Edit: I have uploaded the code to pastebin, as github didn't show the code in tags properly!

Best Regards :)

**Comment by JL2210** [comment]
Just a note, I believe you have to use triple-backticks (```) on the line above and the line below your code for it to be formatted properly. See the [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).

**Comment by D34Dspy** [comment]
> Just a note, I believe you have to use triple-backticks (```) on the line above and the line below your code for it to be formatted properly. See the [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) for more details.

Yeah, I tried. However not all code between the triple-backticks were properly formatted, actually, some code was left out.

**Comment by flobernd** [comment]
> the instruction "pop ebp" (0xC3)

Probably not the problem, but `0xC3` is actually the `RET` instruction.

**Comment by D34Dspy** [comment]
> > the instruction "pop ebp" (0xC3)
> 
> Probably not the problem, but `0xC3` is actually the `RET` instruction.

Oh, my bad, I posted the wrong opcode. (The real one was 0x5D)
I have debugged a little and figured out, that the field _inst in xed_decoded_inst_t was nullptr,
that's why it didn't work I guess. I'll try to research more on this problem, so I can elaborate more.

**Comment by markcharney** [comment]
% obj/examples/xed -de 5d
5D
ICLASS: POP   CATEGORY: POP   EXTENSION: BASE  IFORM: POP_GPRv_58   ISA_SET: I86
SHORT: pop ebp
Encodable! 5D
Identical re-encoding
