### ISSUE TITLE
NOP0F1F operands

### ISSUE THREAD

**Issue by andreas-abel** [intelxed/xed#189]
According to both the Intel and AMD manual, the NOP instruction with 0F 1F encoding takes one (register or memory) operand (with the reg field being 0). This is also how, e.g., objdump disassembles it. However, in XED the instruction has two operands.

**Comment by markcharney** [comment]
XED is right.  I last tried to fix the Intel doc for this in 2012 (according to my email archive).  I think our doc person at the time got it wrong. AMD changed their docs in 2010; Unlike the "NOP page", their opcode map still  (at least last I saw version 3.25 Dec 2017) indicates a full modrm and no /0 restriction.  I should try to fix the docs again...

**Comment by markcharney** [comment]
(BTW you can also look for "Reserved NOP" in volume 3,  section 22.15. Not sure why the NOP page was not updated but I'm sure someone had a reason)
