### ISSUE TITLE
Building examples does not work with default mfile.py flags

### ISSUE THREAD

**Issue by mothran** [intelxed/xed#19]
In order to build the examples directory I had to run:
```bash
./mfile.py --build-dir=./lib/
cd examples
./mfile.py --inc-dir=../lib/
```
The linker fails to find the libxed.a because it always looked in ../lib/ for me, no matter how many linker flags I tweaked in the mfile.py config.
The compiler would fail looking for xed-build-defines.h in the ../includes/* directory without adding the --inc-dir= flag.

This could be just on my machine but was unable to correctly build the examples without these flag modifications.

**Comment by markcharney** [comment]
Hi, I can try to look at your example tomorrow.

I typically build the library & examples by saying this from the directory *above* the examples:

      ./mfile.py examples

one can also build a kit and then use the "kit" examples mfile.py to build the examples from the directory above the examples:
 
     ./mfile.py install
     cd kits
     cd <whatever the kit name is>
     cd examples
     ./mfile.py

That examples mfile.py is really for use in the kits. Not in the source tree.

**Comment by mothran** [comment]
Ahhhh perfect, I was not aware mfile.py was able to accept targets, thanks!  I confirmed that it works and resolved my issues, so I am closing the ticket.

I think it would be helpful for others who come after me if that was included in the main README.
