### ISSUE TITLE
xed_encoder_request_set_rep/ne doesn't appear to have an effect

### ISSUE THREAD

**Issue by jarlostensen** [intelxed/xed#195]
Using ```xed_encoder_request_set_rep/ne``` for REP/NE instructions appears to have no effect, but as per the documentation the REP/NE_ instruction prefix does and generates the correct prefix bytes. Does ```xed_encoder_request_set_rep/ne``` have side effects that are relevant? I've also noticed that some instructions don't encode, whereas NASM (for example) seems to encode them. An example is ```repne stows```.

**Comment by markcharney** [comment]
Thanks for the bug report. Apologies for the delay in responding.

I believe they currently do nothing; I should remove them from the API. The "REP" field is now an encoder-output now so it is currently ignored as an input to the encoder. I'll poke around a little and confirm. But I think this is accurate after a quick glance at stuff.  This is result of a change described below.

To encode a rep stosw, or any "rep"-like operation, XED (recently, in last year or two) defined special forms of the instructions, like rep_stosw. The reason behind this is that the (register or flag) resources used in the rep and non-rep forms are often different and we needed a way to distinguish between these cases. Similar story for 0xF0 lock-prefixed memops.


```
% obj/wkit/bin/xed  -e rep_stosw/16
Request: REP_STOSW EOSZ:1, MODE:1, SMODE:1
Encodable! F366AB
.byte 0xf3,0x66,0xab

% obj/wkit/bin/xed -16 -e rep_stosw
Request: REP_STOSW SMODE:1
Encodable! F3AB
.byte 0xf3,0xab
```

**Comment by markcharney** [comment]
I have a very large set of changes pending. When I push those, this one will be included.

**Comment by psjarlo** [comment]
Great, thanks!
