### ISSUE TITLE
Bugs in pysrc/generator.py

### ISSUE THREAD

**Issue by ctchou** [intelxed/xed#197]
XED commit id: b7231de4c808db821d64f4018d15412640c34113

On lines 1299 and 1326 of pysrc/generator.py, the `ii.iclass` should be replaced by `self.iclass`.

**Comment by markcharney** [comment]
your link didn't point to anything relevant, but I found two instances in die() messages that should be fixed. I have a bunch of commits stacked up. I'll add this change to my upcoming push.

**Comment by markcharney** [comment]
...and thanks.
