### ISSUE TITLE
Question: encoding AVX512 instruction

### ISSUE THREAD

**Issue by jarlostensen** [intelxed/xed#198]
This is probably a dumb question, but I'm trying to use the xed-enc test project to understand how AVX512 instructions are set up for the encoder. I try with the following arguments:

```-64 vpcmpd/512 k1 zmm0 zmm1 IMM:05```

And I get this;
```Encode request:
VPCMPD IMM0:0x5, IMM_WIDTH:8, MODE:2, REG0:K1, REG1:ZMM0, REG2:ZMM1, SMODE:2, VL:2
OPERAND ORDER: REG0 REG1 REG2 IMM0

Could not encode
```

any clues as to what I'm doing wrong? I'd like to do this so that I can encode the instructions in my own application, #inasm64

**Comment by markcharney** [comment]
i am away from my computer but i think you’ll have success with two mask regs. Use k0 if not using write masking. To cut down on versions of instructions, I didn’t make non-write-masking forms that take fewer operands.  I felt like having 3 versions (reg, reg rounding, mem) for each of 3 vector lengths was already a lot. I could have also split out mem broadcast and no write masking and that would have been a lot of versions...

**Comment by psjarlo** [comment]
got it, thanks, I'll try that out
