### ISSUE TITLE
Multiple crashes fuzzing xed elf input with AFL

### ISSUE THREAD

**Issue by mothran** [intelxed/xed#20]
I found quite a collection of crashes with some simple AFL fuzzing of the 'xed' example binary with elf file inputs. 

Here is the output from AFL after 30 minutes.
![AFL output - 30 mins](http://i.imgur.com/MhLJUW3.png)

Many of those 'unique crashes' are duplicates but I have seen crashes in the elf parser as well as in the instruction decoder as well.

Below are my reproduction steps on Linux:
```bash
# grab afl and build it
wget http://lcamtuf.coredump.cx/afl/releases/afl-latest.tgz
tar -xvf ./afl-latest.tgz
cd afl-2.35b

# I prefer to use the afl-clang-fast compiler
cd llvm_mode
make
cd ../../

# build xed with the afl compiler
git clone https://github.com/intelxed/xed.git xed
git clone https://github.com/intelxed/mbuild.git mbuild
cd xed
./mfile.py --cc=../afl-2.35b/afl-clang-fast --cxx=../afl-2.35b/afl-clang-fast++ --build-dir=./lib/
cd examples
./mfile.py --cc=../../afl-2.35b/afl-clang-fast --cxx=../../afl-2.35b/afl-clang-fast++ --inc-dir=../lib/
cd ../../afl-2.35b
mkdir -p ./output/xed/

# start the fuzzer
./afl-fuzz -i ./testcases/others/elf -o ./output/xed -f /tmp/xed_fuzz.elf -- ../xed/examples/obj/examples/xed -i @@
```

I included a .so in the testcases/other/elf/ (/lib/LLVMHello.so), but crashes should start imminently after starting the fuzzer with a single elf file.

I am happy to send a tgz of all the crash samples I have collected if issues arise with reproducing the fuzzer itself.

**Comment by markcharney** [comment]
Very cool!  If you we can work out how to send me some crashes to get started, I would be excited to investigate (or have others help investigate). The examples are not really meant to be robust bulletproof things but the libxed should be!  I would be more interested in examples of issues in libxed, but problems in examples are interesting too. Thanks!

**Comment by mothran** [comment]
Awesome!  Would you mind if I reach out via your @intel email in the git log?

I have not yet duped the crashes using a gdb script yet but AFL does supply a decent one in experimental/crash_triage/triage_crashes.sh

**Comment by markcharney** [comment]
My intel email is fine for small stuff. If the files are very large (many MB), post them somewhere and point me too it (google drive, dropbox, etc.) 

I can feed a bunch of tests in to gdb and see if there is any commonality in the stack traces.

(To build debug add the --debug flag to the compilation line). 

Thanks!

**Comment by markcharney** [comment]
Thanks for the files. I took a quick look. I believe most of the issues appear to be because of malformed elf files tricking the code in to referencing memory that might not be present/accessible. The pointer refs fail at various depths of the code - some in the example sources and some make it deeper in the the libxed where the input bytes are processed. If I somehow validate the accessibility of the input bytes in the example, I suspect that I'll avoid most (all?) of the identified issues. That's just my initial guess though.  Interesting.

**Comment by markcharney** [comment]
I put in a little check before disassembling a region to see if the section being disassembled is within the region the code had mmap()'d. That cut out a big chunk of the segvs. You sent 397 segv'ing elf files. After this one small change I have 86 remaining to stomp out :-)  

If you have a way of generating random byte streams (1..15 hex bytes) and feeding those to the command line that might be more interesting to see if we get any segv's that way.
      % ./obj/examples/xed -64 -d <1...15 hex bytes>

**Comment by markcharney** [comment]
I enabled the limit check for 32b elf binaries too (I didn't realize some tests were 32b) and that knocked out some more segvs.  Down to 16 fails with a ~10line change.

**Comment by markcharney** [comment]
Added a few more checks for symbol table handling and got it down to 0 fails.

Here's my patch: 
https://github.com/intelxed/xed/pull/23

Everything was due to funky elf headers & symbol / string table entries. 
no libxed issues.

**Comment by mothran** [comment]
Awesome! I will look at reformatting the fuzzer to work on just x86 instruction streams a bit later and inform you of any issues I happen to find.

Thanks for all the patches!

Feel free to close the ticket when you see fit, considering you patched up the code and have the regressions.

**Comment by mothran** [comment]
In order to more easily fuzz the instruction decoder itself, is there a command line option to pass in a file or buffer (via stdin) that is raw instructions instead of hex encoded?

**Comment by markcharney** [comment]
Yeah, the command line tool has a couple other options than -i for the native format of the OS:

	-ir raw_input_file        (decode a raw unformatted binary file)
	-ih hex_input_file        (decode a raw unformatted ASCII hex file)

**Comment by mothran** [comment]
Thank you!
