### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [intelxed/xed#21]
I would like to point out that an identifier like "[`_XED_INTERFACE_H_`](https://github.com/intelxed/xed/blob/fcd2d41b2bd8802eed4e620a6836795fbd7ad919/include/public/xed/xed-interface.h#L25 "Update candidate")" [does eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by markcharney** [comment]
good point. I'll fix that. (Probably in January). Thx.

**Comment by markcharney** [comment]
...  either January, or, ah, 5 minutes ago. :-) 
Hopefully, I will push this tomorrow. Thanks

**Comment by markcharney** [comment]
pushed a change to the (new) dev branch.

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/intelxed/xed/commit/85e545d2295805b79b046be8b28e9b2658a74633 "Deletion of some underscores").
