### ISSUE TITLE
monitorx/mwaitx have no_refining_prefix

### ISSUE THREAD

**Issue by 0xd4d** [intelxed/xed#211]
AMD docs don't seem to say that these instructions can't have `66`/`F3`/`F2` prefixes. It also seems like these are the only `AMDONLY` instructions in your files that have `no_refining_prefix`. Is this a copy and paste bug (from `monitor`/`mwait` instructions)?

https://github.com/intelxed/xed/blob/master/datafiles/xed-amd-monitorx.txt

```
xed -64 -d 0F01FA
0F01FA
ICLASS: MONITORX   CATEGORY: MISC   EXTENSION: MONITORX  IFORM: MONITORX   ISA_SET: MONITORX
SHORT: monitorx

xed -64 -d F30F01FA
F30F01FA
ERROR: GENERAL_ERROR Could not decode at offset: 0x0 PC: 0x0: [F30F01FA0000000000000000000000]
```

**Comment by 0xd4d** [comment]
AMD added another instruction that uses a mandatory prefix with the same opcode, https://www.amd.com/system/files/TechDocs/24594.pdf

```diff
    0F 01 FA = MONITORX
+F3 0F 01 FA = MCOMMIT
```

I guess this issue can be closed.

**Comment by markcharney** [comment]
Yeah. Thanks.

I have added MCOMMIT in my local workspace and will push that out with my next batch of changes.
