### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [intelxed/xed#22]
Would you like to [replace any double quotes](https://github.com/intelxed/xed/blob/fcd2d41b2bd8802eed4e620a6836795fbd7ad919/include/public/xed/xed-interface.h#L32 "Check inclusion style") by [angle brackets around file names for include statements](https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by markcharney** [comment]
Not so sure about this one.  Is this really necessary?

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "Draft for the C++ standard specification") in the standard specification for the programming language "C++".

```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```
- How do you think about to avoid "a duplicated file search" here?
- Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Description for include syntax") for header files of your software?

**Comment by rscohn2** [comment]
Markus,

After reading https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html, I
think "" is correct. It allows xed-interface.h to find the other header
files in the current directory, even if they are not in the system include
area or user does not use -I<path-to-xed>. It also prevents issues where
xed-interface.h is in a private directory, but incorrectly pulls in the
rest of the header files from a system dirctory.

Robert

**Comment by elfring** [comment]
There are different opinions about the handling of the involved implementation-defined behaviour.
- Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
- Is there a speed difference measurable if a file is not found there and the search will be retried with “the angle brackets inclusion method”?
