### ISSUE TITLE
Building with --KNC option doesn't work

### ISSUE THREAD

**Issue by a0rland0** [intelxed/xed#221]
Hi,
When I try to build xed with KNC support ("python.exe mfile.py --knc examples") I always get this error:

[ERROR] Did failed to convert opcode VV1 from VV1 0x75 VNP VMAP0   W0 BRDISP8() for map name: legacy-map0 space: legacy legacyesc: N/A legacyopc: N/A mapid: 0 modrm: var imm8: var imm32: no opcpos: 0 priority: 100 search_pattern:
  File "./pysrc/generator.py", line 6354, in <module>
    main()
  File "./pysrc/generator.py", line 6339, in main
    ild.work(agi)
  File "./pysrc\ild.py", line 238, in work
    disp_nts, brdisp_nts, all_state_space)
  File "./pysrc\ild.py", line 333, in get_patterns
    ildutil.mode_space, all_state_space)
  File "./pysrc\ild.py", line 461, in __init__
    mi,insn_map2,opcode2 = self.get_map_opcode_wip()
  File "./pysrc\ild.py", line 674, in get_map_opcode_wip
    genutil.die("Did failed to convert opcode {} from {} for map {}".format(opcode, self.ptrn, mi))
  File "./pysrc\genutil.py", line 83, in die
    traceback.print_stack()

I think the last version I was able to compile was "XED version: [8.20.0-9-g4682a68d]".
Thank you
Best regards
Antonio Orlando

**Comment by markcharney** [comment]
Hi, Can you explain why you need KNC support?

**Comment by a0rland0** [comment]
Hi, 
I have my own disassembler engine that is based on XED datafiles. 
To make sure my engine supports all processors, architectures, etc. I compare the result of both tools to see if they match (after generating millions of opcodes). 
From what I understand the KNC support disables EVEX instructions, and so I always build/compile XED in both modes. 
Since KNC instructions haven't changed in the last version, using version "8.20.0-9-g4682a68d" is more than enough for me.
I shared the error message because it might be an easy fix :)

**Comment by markcharney** [comment]
I'll look at fixing it, but KNC support will be dropped if it causes me any maintenance problems. Thanks for reporting the issue.

**Comment by markcharney** [comment]
I have fixed this in my workspace.  I have been working on a big change to how decoding maps are defined. This fix depends on those changes I have not pushed yet.  I hope to push my  commits externally soon, maybe in the next week or two.  thank you for reporting this issue.

**Comment by a0rland0** [comment]
I'll recheck it when the next version is available. thank you for your feedback and quick fix.

**Comment by markcharney** [comment]
this should be fixed now. let me know if you are  still having issues. thx for reporting.
