### ISSUE TITLE
py3 support for xed

### ISSUE THREAD

**Issue by rscohn2** [intelxed/xed#24]
The py3 branch in https://github.com/rscohn2/mbuild works with python2 and python3

The py3 branch in https://github.com/rscohn2/xed builds the tests with python2 and python3

The tests pass with python2 and fail with python3. Here is an example:

    py3mbuild) rscohn1@ubuntu-xenial:~/workspaces$ xed-ref/build/examples/xed-ex3 -64 vaddps ymm3 k1 ymm1 ymm2
    Encode request:
    VADDPS MODE:2, REG0:YMM3, REG1:K1, REG2:YMM1, REG3:YMM2, SMODE:2
    OPERAND ORDER: REG0 REG1 REG2 REG3 

    Encodable! 62F1742958DA
    (py3mbuild) rscohn1@ubuntu-xenial:~/workspaces$ xed/build/examples/xed-ex3 -64 vaddps ymm3 k1 ymm1 ymm2
    Encode request:
    VADDPS MODE_FIRST_PREFIX, REG0:YMM3, REG1:K1, REG2:YMM1, REG3:YMM2, SMODE:2
    OPERAND ORDER: REG0 REG1 REG2 REG3 

    Encodable! 62F1742958DA
    (py3mbuild) 

I tried inspecting the output of the generator, but python2 and python3 emit the functions in different order, so diff does not help. It may be beneficial to sort the functions before emitting so it is not sensitive to python versions. Spot checking shows no differences.

@markcharney: Can you look at this? I think we are close.

**Comment by markcharney** [comment]
#47 merged
