### ISSUE TITLE
Support for VIA instructions with XED_CHIP_ALL

### ISSUE THREAD

**Issue by woodruffw** [intelxed/xed#250]
Hi there!

I've been running [mishegos](https://github.com/trailofbits/mishegos) against XED, and I noticed that a couple of VIA (PadLock) specific instructions are referenced in the codebase but aren't decoded properly with `XED_CHIP_ALL`.

In particular: neither `XSTORE` not `MONTMUL` is decoded. All of the test cases that mishegos found include `REP` / `REPNZ` prefixes, so it's possible that that's the rep-family prefixes are what's snarling XED up.

Here are some specific test cases:

* `2e6667f20fa7c0` -- `REPNZ XSTORE`
* `65f2f2f30fa6c0` -- `REP MONTMUL`

---

Raw table from mishegos below (feel free to ignore this):

input | worker
-- | --

  | ./src/worker/xed/xed.so | ./src/worker/zydis/zydis.so | ./src/worker/bddisasm/bddisasm.so | ./src/worker/iced/iced.so
-- | -- | -- | -- | --
2e6667f20fa7c0 | (0 / 0) | (0 / 0) | REPNZ XSTORE (7 / 12) | addr32 repnz xstore (7 / 19)
f267470fa7c0 | (0 / 0) | (0 / 0) | REPNZ XSTORE (6 / 12) | addr32 repnz xstore (6 / 19)
65f267470fa7c0 | (0 / 0) | (0 / 0) | REPNZ XSTORE (7 / 12) | addr32 repnz xstore (7 / 19)
3e65f267470fa7c0 | (0 / 0) | (0 / 0) | REPNZ XSTORE (8 / 12) | addr32 repnz xstore (8 / 19)
f3656536450fa6c0 | (0 / 0) | rep montmul (8 / 11) | REP MONTMUL (8 / 11) | rep montmul (8 / 11)
65f2f2f30fa6c0 | (0 / 0) | rep montmul (7 / 11) | REP MONTMUL (7 / 11) | rep montmul (7 / 11)
f3f2470fa7c0 | (0 / 0) | (0 / 0) | REPNZ XSTORE (6 / 12) | repnz xstore (6 / 12)
64262ef24c0fa7c0 | (0 / 0) | (0 / 0) | REPNZ XSTORE (8 / 12) | repnz xstore (8 / 12)
2ef236260fa7c0 | (0 / 0) | (0 / 0) | REPNZ XSTORE (7 / 12) | repnz xstore (7 / 12)

**Comment by markcharney** [comment]
Hi. So I have  XSTORE  requiring F3 prefix. You supplied F2.  That's why XED didn't recognize it.  Are you saying XSTORE works with F2 as well?

**Comment by woodruffw** [comment]
It took quite a bit of digging to find a copy of the VIA PadLock Programmer's Guide online, but it looks like `REPNZ` is indeed undefined for `XSTORE`:

> REP Prefix
> • The REPNE prefix is undefined.

So XED's behavior here is correct, and the consensus behavior is wrong. Sorry for the noise; I'll file issues with those other decoders!

**Comment by woodruffw** [comment]
On the other hand, the guide does document `REP MONTMUL` as valid:

![image](https://user-images.githubusercontent.com/3059210/104750887-abeef180-5722-11eb-8353-4e8c6b35c1fd.png)

I'll try to reduce those two `REP MONTMUL` cases a bit, since they have a few conflicting prefixes in them.

**Comment by markcharney** [comment]
So for rep montmul, they show it with  an f3 in  that  doc  you cite  (top of section  5.1)  and they mention (in your  quote  above) that   repne (f2) causes undefined behavior. 

So I'm gonna stick with F3 on that one unless someone has better information  to share.
Ok to close this?

**Comment by woodruffw** [comment]
Yeah, I think this is okay to close. I'm going to see if I can get my hands on a C3 to test with, since the Iced maintainer suspects that these instructions _might_ not `#UD` with `F2`, just do something underspecified. But I understand if "underspecified" versus "invalid" isn't a distinction that XED cares about, especially for instructions this obscure.

**Comment by markcharney** [comment]
Ok.  In  my experience, "undefined"  is sometimes  used to mean behavior was not validated  or varied across steppings or something. Basically not something one can rely  upon.  Let   me  know if you  find other  things to  ponder :-)
