### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by jplopezy** [intelxed/xed#258]
I trying to compile it on windows 10 x64, python 3.4

error

C:\xed>mfile.py
[UCRT Version] 10.0.10240.0
[FOUND MS VERSION] 14
[PYTHON VERSION] 3.4.0
[GIT VERSION] 12.0.1-7-gc6c070f
[EXTF PROCESSING] C:/xed/datafiles/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/files-xregs.cfg
[EXTF PROCESSING] C:/xed/datafiles/via/files-via-padlock.cfg
[EXTF PROCESSING] C:/xed/datafiles/amd/files-amd.cfg
[EXTF PROCESSING] C:/xed/datafiles/amd/amdxop/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/mpx/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/cet/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/rdrand/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/glm/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/sha/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/xsaveopt/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/xsaves/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/xsavec/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/clflushopt/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/rdseed/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/fsgsbase/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/smap/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/sgx/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/rdpid/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/pt/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/tremont/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/movdir/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/waitpkg/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/cldemote/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/sgx-enclv/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/avx/files.cfg
[Clearing file list for type dec-spine: [ C:/xed/datafiles/xed-spine.txt ]]
[EXTF PROCESSING] C:/xed/datafiles/ivbavx/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/hswavx/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/hswbmi/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/hsw/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/bdw/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/skl/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/skx/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/pku/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/clwb/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/clx/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/vnni/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/cpx/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/avx512-bf16/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/knl/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/knm/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/4fmaps-512/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/4vnniw-512/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/vpopcntdq-512/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/avx512f/shared-files.cfg
[Clearing file list for type dec-spine: [ C:/xed/datafiles/avx/avx-spine.txt ]]
CONSIDERING SOURCE C:\xed\datafiles\knc\xed-operand-values-interface-uisa.c source 1
ADDING SOURCE C:\xed\datafiles\knc\xed-operand-values-interface-uisa.c source 1
[EXTF PROCESSING] C:/xed/datafiles/avx512f/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/avx512cd/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/avx512-skx/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/cnl/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/avx512ifma/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/avx512vbmi/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/icl/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/wbnoinvd/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/pconfig/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/bitalg/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/vbmi2/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/gfni-vaes-vpcl/files-sse.cfg
[EXTF PROCESSING] C:/xed/datafiles/gfni-vaes-vpcl/files-avx-avx512.cfg
[EXTF PROCESSING] C:/xed/datafiles/vpopcntdq-vl/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/tgl/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/vp2intersect/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/keylocker/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/adl/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/hreset/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/avx-vnni/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/spr/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/uintr/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/amx-spr/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/enqcmd/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/tsx-ldtrk/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/serialize/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/future/files.cfg
[EXTF PROCESSING] C:/xed/datafiles/tdx/files.cfg
[EMIT BUILD DEFINES HEADER FILE]
[WRITING] obj/DEC-OUT.txt
[WRITING] obj/ENC-OUT.txt
[WRITING] obj/ENC-ERR.txt
[WRITING] obj/DEC-ERR.txt
[ENC-GEN] Return code: 0
[DEC-GEN] Return code: 0
[MBUILD WARNING] Command execution failed. Waiting for remaining jobs and exiting.
[COMMAND     ] "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe" -IC:/xed/include/private -IC:/xed/include/public/xed -IC:/xed/include/public -Iobj -Iobj/include-private     /nologo  /MT  /favor:EM64T  /W4 /WX /wd4091 /wd4127 /wd4505 /wd4702 /wd4244 /wd4292 /DXED_GIT_VERSION="12.0.1-7-gc6c070f" /DXED_AMD_ENABLED /DXED_VIA_ENABLED /DXED_AVX /DXED_SUPPORTS_AVX512 /DXED_MPX /DXED_CET /DXED_SUPPORTS_SHA /DXED_SUPPORTS_WBNOINVD /DXED_DECODER /DXED_ENCODER /DXED_SUPPORTS_LZCNT_TZCNT /DXED_BUILD /c /Foobj/xed3-phash-lu-vv2.obj C:/xed/obj/xed3-phash-lu-vv2.c
[EXIT_STATUS ] 399
[STDERR]

COMMAND ENCOUNTERD AN EXCEPTION
Traceback (most recent call last):
  File "C:\xed\..\mbuild\mbuild\util.py", line 1048, in run
    **self.kwargs)
  File "C:\Python34\lib\subprocess.py", line 848, in __init__
    restore_signals, start_new_session)
  File "C:\Python34\lib\subprocess.py", line 1104, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

[MBUILD WARNING] Command execution failed. Waiting for remaining jobs and exiting.
[COMMAND     ] "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe" -IC:/xed/include/private -IC:/xed/include/public/xed -IC:/xed/include/public -Iobj -Iobj/include-private     /nologo  /MT  /favor:EM64T  /W4 /WX /wd4091 /wd4127 /wd4505 /wd4702 /wd4244 /wd4292 /DXED_GIT_VERSION="12.0.1-7-gc6c070f" /DXED_AMD_ENABLED /DXED_VIA_ENABLED /DXED_AVX /DXED_SUPPORTS_AVX512 /DXED_MPX /DXED_CET /DXED_SUPPORTS_SHA /DXED_SUPPORTS_WBNOINVD /DXED_DECODER /DXED_ENCODER /DXED_SUPPORTS_LZCNT_TZCNT /DXED_BUILD /c /Foobj/xed-reg-class.obj C:/xed/src/common/xed-reg-class.c
[EXIT_STATUS ] 399
[STDERR]

COMMAND ENCOUNTERD AN EXCEPTION
Traceback (most recent call last):
  File "C:\xed\..\mbuild\mbuild\util.py", line 1048, in run
    **self.kwargs)
  File "C:\Python34\lib\subprocess.py", line 848, in __init__
    restore_signals, start_new_session)
  File "C:\Python34\lib\subprocess.py", line 1104, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

[MBUILD WARNING] Command execution failed. Waiting for remaining jobs and exiting.
[COMMAND     ] "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe" -IC:/xed/include/private -IC:/xed/include/public/xed -IC:/xed/include/public -Iobj -Iobj/include-private     /nologo  /MT  /favor:EM64T  /W4 /WX /wd4091 /wd4127 /wd4505 /wd4702 /wd4244 /wd4292 /DXED_GIT_VERSION="12.0.1-7-gc6c070f" /DXED_AMD_ENABLED /DXED_VIA_ENABLED /DXED_AVX /DXED_SUPPORTS_AVX512 /DXED_MPX /DXED_CET /DXED_SUPPORTS_SHA /DXED_SUPPORTS_WBNOINVD /DXED_DECODER /DXED_ENCODER /DXED_SUPPORTS_LZCNT_TZCNT /DXED_BUILD /c /Foobj/xed-encoder-hl.obj C:/xed/src/enc/xed-encoder-hl.c
[EXIT_STATUS ] 399
[STDERR]

COMMAND ENCOUNTERD AN EXCEPTION
Traceback (most recent call last):
  File "C:\xed\..\mbuild\mbuild\util.py", line 1048, in run
    **self.kwargs)
  File "C:\Python34\lib\subprocess.py", line 848, in __init__
    restore_signals, start_new_session)
  File "C:\Python34\lib\subprocess.py", line 1104, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

[MBUILD WARNING] Command execution failed. Waiting for remaining jobs and exiting.
[COMMAND     ] "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe" -IC:/xed/include/private -IC:/xed/include/public/xed -IC:/xed/include/public -Iobj -Iobj/include-private     /nologo  /MT  /favor:EM64T  /W4 /WX /wd4091 /wd4127 /wd4505 /wd4702 /wd4244 /wd4292 /DXED_GIT_VERSION="12.0.1-7-gc6c070f" /DXED_AMD_ENABLED /DXED_VIA_ENABLED /DXED_AVX /DXED_SUPPORTS_AVX512 /DXED_MPX /DXED_CET /DXED_SUPPORTS_SHA /DXED_SUPPORTS_WBNOINVD /DXED_DECODER /DXED_ENCODER /DXED_SUPPORTS_LZCNT_TZCNT /DXED_BUILD /c /Foobj/xed-machine-mode-enum.obj C:/xed/obj/xed-machine-mode-enum.c
[EXIT_STATUS ] 399
[STDERR]

COMMAND ENCOUNTERD AN EXCEPTION
Traceback (most recent call last):
  File "C:\xed\..\mbuild\mbuild\util.py", line 1048, in run
    **self.kwargs)
  File "C:\Python34\lib\subprocess.py", line 848, in __init__
    restore_signals, start_new_session)
  File "C:\Python34\lib\subprocess.py", line 1104, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

ABORT: Library build failed

**Comment by markcharney** [comment]
strange. no idea. you ever use your compiler before? you know it is working and installed conventionally?

random thought: try upgrading your python version. later pythons handle unicode better. I see you have a “foreign” (well, to me. non english) language in use.

**Comment by jplopezy** [comment]
Fixed, I tried it on a clean install and it worked.

**Comment by wizche** [comment]
Same issue here, looks like that its running 
`C:/Program Files/Microsoft Visual Studio/2022/Community/VC/bin/amd64/cl.exe`
which doesnt exists instead of 
`C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.31.31103/bin/Hostx64/x64/cl.exe`

**Comment by marjevan** [comment]
VS 2022 build support will be added soon.
