### ISSUE TITLE
Building error: xed/xed-enc2-m64-a64.h: No such file or directory

### ISSUE THREAD

**Issue by losfree** [intelxed/xed#272]
when following readme , there's an error with last command
![image](https://user-images.githubusercontent.com/48171774/118469519-59f1c300-b738-11eb-996b-66b664117fb0.png)  
  
root@ubuntu:~/Downloads/xed/kits/xed-install-base-2021-05-17-lin-x86-64/examples# ./mfile.py 
[PYTHON VERSION] 3.8.5
[CMDLINE] /root/Downloads/xed/kits/xed-install-base-2021-05-17-lin-x86-64/examples/obj/xed
[BUILDING EXAMPLES] 
R: 4 P: 32 C: 0 E: 0 / 2 msecs 
R: 4 P: 31 C: 1 E: 0 / 47 msecs 
	BUILT: /root/Downloads/xed/kits/xed-install-base-2021-05-17-lin-x86-64/examples/obj/avltree.o
R: 4 P: 30 C: 2 E: 0 / 66 msecs 
	BUILT: /root/Downloads/xed/kits/xed-install-base-2021-05-17-lin-x86-64/examples/obj/xed-min.o
R: 4 P: 29 C: 3 E: 0 / 68 msecs 
	BUILT: /root/Downloads/xed/kits/xed-install-base-2021-05-17-lin-x86-64/examples/obj/xed-tester.o
R: 4 P: 28 C: 4 E: 0 / 69 msecs 
	BUILT: /root/Downloads/xed/kits/xed-install-base-2021-05-17-lin-x86-64/examples/obj/xed-reps.o
R: 4 P: 27 C: 5 E: 0 / 112 msecs 
	BUILT: /root/Downloads/xed/kits/xed-install-base-2021-05-17-lin-x86-64/examples/obj/xed-tables.o
R: 4 P: 26 C: 6 E: 0 / 119 msecs 
	BUILT: /root/Downloads/xed/kits/xed-install-base-2021-05-17-lin-x86-64/examples/obj/xed-size.o
R: 4 P: 26 C: 7 E: 0 / 137 msecs 
	BUILT: /root/Downloads/xed/kits/xed-install-base-2021-05-17-lin-x86-64/examples/obj/xed-find-special.o
R: 4 P: 25 C: 8 E: 0 / 138 msecs 
	BUILT: /root/Downloads/xed/kits/xed-install-base-2021-05-17-lin-x86-64/examples/obj/xed-dll-discovery.o
[MBUILD WARNING] Command execution failed. Waiting for remaining jobs and exiting.
R: 3 P: 25 C: 9 E: 1 / 162 msecs 
[COMMAND     ] gcc -I. -I../include        -m64  -std=c99  -pedantic  -Wall -Wunused -Werror -Wno-long-long -Wno-unknown-pragmas -fmessage-length=0 -pipe -fomit-frame-pointer -fno-exceptions -Wno-format -Wno-format-security -Wstrict-prototypes -Wwrite-strings -Wredundant-decls  -c -o obj/xed-enc2-1.o /root/Downloads/xed/kits/xed-install-base-2021-05-17-lin-x86-64/examples/xed-enc2-1.c
[EXIT_STATUS ] 1
[STDERR] 
/root/Downloads/xed/kits/xed-install-base-2021-05-17-lin-x86-64/examples/xed-enc2-1.c:20:10: fatal error: xed/xed-enc2-m64-a64.h: No such file or directory
   20 | #include "xed/xed-enc2-m64-a64.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

[MBUILD WARNING] Command execution failed. Waiting for remaining jobs and exiting.
R: 2 P: 25 C: 10 E: 2 / 165 msecs 
[COMMAND     ] gcc -I. -I../include        -m64  -std=c99  -pedantic  -Wall -Wunused -Werror -Wno-long-long -Wno-unknown-pragmas -fmessage-length=0 -pipe -fomit-frame-pointer -fno-exceptions -Wno-format -Wno-format-security -Wstrict-prototypes -Wwrite-strings -Wredundant-decls  -c -o obj/xed-enc2-2.o /root/Downloads/xed/kits/xed-install-base-2021-05-17-lin-x86-64/examples/xed-enc2-2.c
[EXIT_STATUS ] 1
[STDERR] 
/root/Downloads/xed/kits/xed-install-base-2021-05-17-lin-x86-64/examples/xed-enc2-2.c:20:10: fatal error: xed/xed-chk-enc2-m64-a64.h: No such file or directory
   20 | #include "xed/xed-chk-enc2-m64-a64.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

[MBUILD WARNING] Command execution failed. Waiting for remaining jobs and exiting.
R: 1 P: 25 C: 11 E: 3 / 183 msecs 
[COMMAND     ] gcc -I. -I../include        -m64  -std=c99  -pedantic  -Wall -Wunused -Werror -Wno-long-long -Wno-unknown-pragmas -fmessage-length=0 -pipe -fomit-frame-pointer -fno-exceptions -Wno-format -Wno-format-security -Wstrict-prototypes -Wwrite-strings -Wredundant-decls  -c -o obj/xed-enc2-3.o /root/Downloads/xed/kits/xed-install-base-2021-05-17-lin-x86-64/examples/xed-enc2-3.c
[EXIT_STATUS ] 1
[STDERR] 
/root/Downloads/xed/kits/xed-install-base-2021-05-17-lin-x86-64/examples/xed-enc2-3.c:20:10: fatal error: xed/xed-enc2-m64-a64.h: No such file or directory
   20 | #include "xed/xed-enc2-m64-a64.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

R: 0 P: 25 C: 12 E: 3 / 196 msecs 
	BUILT: /root/Downloads/xed/kits/xed-install-base-2021-05-17-lin-x86-64/examples/obj/xed-ex6.o
ABORT: XED EXAMPLES build failed
root@ubuntu:~/Downloads/xed/kits/xed-install-base-2021-05-17-lin-x86-64/examples# 

How can I get this file?
based on ubuntu20.04

**Comment by mjcharne** [comment]
Ooops. Sorry.  The enc2 examples require a different  build for the  non-example part of XED. The "enc2' builds are longer and create a couple more libraries so  they are not active by  default. I should make the build from examples example aware of the different builds and not build  the enc2 examples if a non-enc2 build was done for the  kit.

To build  with enc2,  please see the [wiki here](https://github.com/intelxed/xed/wiki/The-fast-encoder---enc2)
