### ISSUE TITLE
How to make the xed.lib file size MUCH smaller ?

### ISSUE THREAD

**Issue by Victor6799** [intelxed/xed#296]
Right now as it stands this file sits at nearly 16MB. All that I would like to accomplish is to decode (disassemble) binary code on the fly 1-15 bytes at a time. Is it possible to statically link the xed.lib file with my project and still have the overall size no larger than 1-2MB ?

**Comment by marjevan** [comment]
Please check https://github.com/intelxed/xed#binary-size

**Comment by Victor6799** [comment]
Thanks again @marjevan.  I need to statically link the xed.lib file for windows into my KMDF device driver project. Where can I find any documentation on how to strip the binaries or make just the decoder no encoder ? Thank you.

**Comment by marjevan** [comment]
Hi,
You can use the "--no-encoder" build knob.
Please note the latest [External Release v2023.06.07](https://github.com/intelxed/xed/commit/4dc77137f651def2ece4ac0416607b215c18e6e4) improves decoder code size.
