### ISSUE TITLE
ENQCMDS should have CPL=0

### ISSUE THREAD

**Issue by sehftz** [intelxed/xed#311]
Currently in [this file](https://github.com/intelxed/xed/blob/main/datafiles/apx-f/apx-f-isa.xed.txt#L20033) the ENQCMDS instruction has CPL=3, however in Intel's SDM Volume 2 Chapter 3.3 "ENQCMDS—Enqueue Command Supervisor", it says "The ENQCMDS instruction may be executed only if CPL = 0".

**Comment by marjevan** [comment]
Thanks for your report.
A fix will be available with the upcoming external release.

**Comment by marjevan** [comment]
Solved this in https://github.com/intelxed/xed/commit/6d87b5481aa53b5ab1fc2b5a5622759c46746bf9
