### ISSUE TITLE
LGDT should have CPL=0

### ISSUE THREAD

**Issue by sehftz** [intelxed/xed#312]
Currently in [this file](https://github.com/intelxed/xed/blob/main/datafiles/xed-isa.txt#L4081) the LGDT instruction has CPL=3, however in Intel's SDM Volume 2 Chapter 3.3 "LGDT/LIDT—Load Global/Interrupt Descriptor Table Register", it specifies the exception "#GP(0) If the current privilege level is not 0.".

**Comment by marjevan** [comment]
Thanks for your report.
A fix will be available with the upcoming external release.

**Comment by marjevan** [comment]
Solved this in https://github.com/intelxed/xed/commit/6d87b5481aa53b5ab1fc2b5a5622759c46746bf9
