### ISSUE TITLE
VMCALL should have CPL=0

### ISSUE THREAD

**Issue by sehftz** [intelxed/xed#313]
Currently in [this file](https://github.com/intelxed/xed/blob/main/datafiles/xed-isa.txt#L4878) the VMCALL instruction has CPL=3, however in Intel's SDM Volume 3 Chapter 31.3 "VMCALL—Call to VM Monitor", it specifies the following operation:
```
ELSIF CPL > 0
    THEN #GP(0);
```

**Comment by marjevan** [comment]
Thanks for your report.
A fix will be available with the upcoming external release.

**Comment by marjevan** [comment]
Solved this in https://github.com/intelxed/xed/commit/6d87b5481aa53b5ab1fc2b5a5622759c46746bf9
