### ISSUE TITLE
Missing two header files in main branch

### ISSUE THREAD

**Issue by yeongseon607** [intelxed/xed#316]
Cloned the latest main branch on 1/3/2024, but xed-cpuid-rec-enum.h and xed-cpuid-group-enum.h are NOT in the main branch. Searched both of include\private and include\public\xed but could not find them.

**Comment by yeongseon607** [comment]
They were under obj\wkit\include\xed.

**Comment by marjevan** [comment]
These files are automatically generated during the build process.
