### ISSUE TITLE
More open development

### ISSUE THREAD

**Issue by Serial-ATA** [intelxed/xed#327]
Is there any chance of there being more open development? With the current external release system, PRs will sit for months after being accepted.

Right now, I'm doing a refactor of `pysrc` that I've been splitting into small chunks for easier review. I have to hold off between changes though, as I don't know the state of the repo until the next external release.

**Comment by marjevan** [comment]
Hello,

Thank you for your contribution - it's truly valued and welcomed.
XED is internally developed at Intel.
We're actively improving our external release process to enable more frequent releases to the public.

**Comment by Serial-ATA** [comment]
> We're actively improving our external release process to enable more frequent releases to the public.

That's good to hear, thanks for working on that.

Out of curiosity though, is there any reason that it must be developed internally? Or does it just ease the process?

**Comment by marjevan** [comment]
There are internal factors that necessitate developing the tool internally.
