### ISSUE TITLE
FMA: VFMADDRND231PD instruction missing?

### ISSUE THREAD

**Issue by tremalrik** [intelxed/xed#329]
According to the Intel SDM rev 084, volume 2C, page 5-207, there exists an instruction `VFMADDRND231PD ymm0, ymm1, ymm2/m256, imm8` with the encoding `VEX.DDS.256.66.0F3A.W1 B8 /r /ib` (as well as a 128-bit form) that is apparently a part of the FMA instruction set (its "CPUID Feature Flag" is listed as "FMA")

XED does not appear to recognize this instruction encoding: as best I can tell, running something like `xed -64 -d c4 e3 fd b8 08 00` should presumably produce something like `vfmaddrnd231pd ymm1, ymm0, ymmword ptr [rax], 0x0` but instead I get a general error.

Is this an actual instruction that XED should support?  (This particular instruction seems to have started showing up in the SDM only from rev 082 onwards (released december 2023) even though it supposedly is a part of an instruction set extension  that's been around since at least 2013.)

**Comment by marjevan** [comment]
Thank you for this report! 
The instruction is indeed incorrect and will be removed from the SDM in the next update, expected next month. 
XED should not support this instruction.
