### ISSUE TITLE
Possible bug in evex scanner

### ISSUE THREAD

**Issue by a0rland0** [intelxed/xed#334]
Hi,
I wonder if the "evex_scanner" function (exists on xed-ild.c) has a bug on line 1282:

1282: if (evex1.coarse.map == 0)

because it will always include the "rexb4" field in the same test.
Maybe it should be a conditional test using "#if defined(XED_APX)" and "if (apx_supported(d))" with "evex1.apx.map" instead.
Thanks
Cheers

**Comment by marjevan** [comment]
Thank you for reporting this issue.

You are correct - when APX is enabled, XED ILD should account for the three lower map bits. 
While XED still correctly flags this as an illegal instruction, the reported instruction length and error type differ.

I am working on a fix, which will be included in the upcoming external release.
