### ISSUE TITLE
build with option "--no-encoder" broken

### ISSUE THREAD

**Issue by mcyril** [intelxed/xed#41]
in the script file xed_mbuild.py:1473

```python
    if ['encoder'] and env['decoder']:
         nongen_lib_sources.extend(_get_src(env,'encdec'))
```

the env[] missing. I suppose it should be:

```python
    if env['encoder'] and env['decoder']:
         nongen_lib_sources.extend(_get_src(env,'encdec'))
```

**Comment by markcharney** [comment]
oops and thanks...

**Comment by markcharney** [comment]
Just created #42  with a fix for this (and some other stuff)

**Comment by markcharney** [comment]
This should be fixed. Let me know if you encounter more issues. Thanks for reporting this!

**Comment by mcyril** [comment]
works like a charm, thank you!
