### ISSUE TITLE
EIP relative addressing decoded as RIP relative

### ISSUE THREAD

**Issue by athre0z** [intelxed/xed#53]
With instructions that have a `67` address size override prefix, XED sets the base register to `RIP` rather than `EIP` even though it correctly detects the EASZ as 32 bits.

```
➜  xed git:(master) ✗ obj/examples/xed-ex1 -64 67 13 2d ee fb 15 35                                                                                 
Attempting to decode: 67 13 2d ee fb 15 35 
iclass ADC	category BINARY	ISA-extension BASE	ISA-set I86
instruction-length 7
operand-width 32
effective-operand-width 32
effective-address-width 32
stack-address-width 64
iform-enum-name ADC_GPRv_MEMv
iform-enum-name-dispatch (zero based) 10
iclass-max-iform-dispatch 18
Operands
#   TYPE               DETAILS        VIS  RW       OC2 BITS BYTES NELEM ELEMSZ   ELEMTYPE   REGCLASS
#   ====               =======        ===  ==       === ==== ===== ===== ======   ========   ========
0   REG0              REG0=EBP   EXPLICIT  RW         V   32     4     1     32        INT        GPR
1   MEM0           (see below)   EXPLICIT   R         V   32     4     1     32        INT    INVALID
2   REG1           REG1=RFLAGS SUPPRESSED  RW         Y   32     4     1     32        INT      FLAGS
Memory Operands
  0    read BASE= RIP/ IP DISPLACEMENT_BYTES= 4 0x000000003515fbee base10=890633198 ASZ0=32
  MemopBytes = 4
FLAGS:
   reads-rflags of-mod sf-mod zf-mod af-mod pf-mod cf-tst cf-mod 
       read:                            cf  mask=0x1
    written:             of sf zf af pf cf  mask=0x8d5
  undefined:                                mask=0x0
ATTRIBUTES: SCALABLE 
67 PREFIX
Number of legacy prefixes: 1 
ISA SET: [I86]
```

Intel SDM:
> RIP-relative addressing is enabled by 64-bit mode, not by a 64-bit address-size. The use of the address-size prefix does not disable RIP-relative addressing. The effect of the address-size prefix is to truncate and zero-extend the computed effective address to 32 bits.

**Comment by markcharney** [comment]
Check out issue #48.  I think this is a duplicate (for which I literally just minutes ago pushed a first cut at a solution).

**Comment by athre0z** [comment]
Nope, I think that's something different, same output on that branch.

**Comment by markcharney** [comment]
Yes, this rip rel addressing representation is a different issue.  I expect to have a fix for this for later next week.  Thank you for reporting this issue.

**Comment by markcharney** [comment]
if the testing passes, check out this branch #54 and let me know if it addresses your issue. Thanks.

**Comment by athre0z** [comment]
Looks good to me. Again, thanks for the lightning fast fix!
