### ISSUE TITLE
Wrong #UD conditions for instructions with mask-register

### ISSUE THREAD

**Issue by flobernd** [intelxed/xed#56]
Hi there,

while using some random data, I noticed XED beeing unable to decode certain instructions if one of the following conditions are met (64-bit mode):
```
EVEX
1. modrm.reg encodes a MASK register and EVEX.R   !=    0 (correct behavior)
2. modrm.reg encodes a MASK register and EVEX.R'  !=    0 (correct behavior)
3. modrm.rm  encodes a MASK register and EVEX.B   !=    0 (should be ignored)

VEX
4. VEX.vvvv  encodes a MASK register and VEX.vvvv != 1xxx
5. modrm.reg encodes a MASK register and VEX.R    !=    0 (might be correct)
6. modrm.rm  encodes a MASK register and VEX.B    !=    0
```
I did not find VEX-specific information about mask-register encoding, but according to table 2.33 (page 99) and table 2.39 (page 102/103) (Intel® 64 and IA-32 Architectures Software Developer’s Manual, March 2017)  case `3.` should not #UD for EVEX-instructions (EVEX.B is ignored instead).

Are these tables valid for VEX and MVEX instructions as well or do these ones follow different reg-encoding/#UD rules?

If they are valid, case `6.` should be handled in the same way as case `3.` and for case `4.` only bits [2:0] are used, so I guess ignoring the most-significant bit of `.vvvv` should be the correct way of handling this one.

In addition `EVEX.R'` should always be ignored in non 64-bit modes and not cause a decoding-error.

**Comment by markcharney** [comment]
Thanks. I'll take a look.

MVEX (KNC's version of EVEX) is not in the SDM. It was its own separate thing.

**Comment by flobernd** [comment]
I took a look into the KNC ISA reference manual and found this text, which confirms to just ignore the MSB, if a mask-register is encoded in `MVEX.vvvv`:
> It can encode any of the lower 16 zmm vector registers, or using the low 3 bits to encode a vector mask register as a source operand. 

(Intel® Xeon Phi™ Coprocessor Instruction Set Architecture Reference Manual, September 2012, page 42)

I just created a new table with all possible cases:
```
VEX: (implying table 2.39 is valid for VEX)
VEX.vvvv  encodes a MASK register (MSB should be ignored)
modrm.reg encodes a MASK register (VEX.R   != 0 -> #UD)
modrm.rm  encodes a MASK register (VEX.B should be ignored)

EVEX:
EVEX.vvvv encodes a MASK register (MSB should be ignored)
modrm.reg encodes a MASK register (EVEX.R  != 0 -> #UD)
modrm.reg encodes a MASK register (EVEX.R' != 0 -> #UD)
modrm.rm  encodes a MASK register (EVEX.B should be ignored)

MVEX:
MVEX.vvvv encodes a MASK register (MSB should be ignored)
modrm.reg encodes a MASK register (don't know)
modrm.reg encodes a MASK register (don't know)
modrm.rm  encodes a MASK register (don't know)
```

**Comment by markcharney** [comment]
Thanks for looking at the old docs. Over the years, I've found enough errors in the docs that, when I can, I usually check the hardware directly or have someone look at the RTL for a couple of designs. I should have a more complete answer in a couple of days. For EVEX.vvvv, I believe the designs ignore EVEX.vvvv[3] in 32b mode but  require that bit to be 1 in 64b mode.  I'll work with the doc people to have the VEX/EVEX #UD stuff improved for mask regs.

**Comment by markcharney** [comment]
It is late here, but if I'm reading things right, EVEX.vvvv never encodes a mask register (at least not yet; I guess anything is possible in the future at which point a rule will be created). So that part appears to be moot.

In 64b: when encoding a mask reg: VEX.B is ignored, VEX.vvvv[3] must be 1, and VEX.R must be 1.

At this point, I do not plan to do anything different for MVEX than what I have planned for EVEX.

**Comment by flobernd** [comment]
Thanks for your reply! Yes, you are right, EVEX.vvvv never encodes a mask register in the current ISA, but MVEX.vvvv does for some instructions (e.g. `vpaddsetcd`).

**Comment by markcharney** [comment]
I pushed a change (5b3b0ac) that should partially address this issue - at least for 64b EVEX/VEX.

**Comment by flobernd** [comment]
I finally got to test your fix and it looks good for MASK registers, but there seems to be a problem with GPR registers as well. 

XED decodes  `62 C1 7F 28 2D 0B` as `vcvtsd2si ecx, qword ptr [r11]`, ignoring the `R'` field beeing 0 (should #UD according to the latest SDM, page 103).

**Comment by markcharney** [comment]
you are correct... consider it on my radar again...

**Comment by markcharney** [comment]
I have implemented a small modification for the EVEX uses of GPR32_R and GPR64_R in mode64 patterns. I'll push it next week.
