### ISSUE TITLE
xed_operand_values_has_modrm_byte returns wrong field

### ISSUE THREAD

**Issue by OZ1** [intelxed/xed#65]
consider the following instruction
48 2B E0 sub rsp, rax
it has REX=48, opcode=2B and modrm=E0 bytes

xed_decoded_inst_s::has_modrm = 1
xed_decoded_inst_s::modrm_byte = E0
xed_decoded_inst_s::modrm = 0

along with has_modrm and modrm_byte fields the structure has modrm field which is not filled in

xed_operand_values_has_modrm_byte which (according to its name) is supposed to return has_modrm=1 field, but returns modrm=0 field instead

FIX should be in change of line 237 in xed-operand-values-interface.c from
    return xed3_operand_get_modrm(p);
to
    return xed3_operand_get_has_modrm(p);

what is the meaning of field modrm? maybe it should be deleted or deprcated if not used?

**Comment by markcharney** [comment]
yep. thx. fixing this now.

**Comment by markcharney** [comment]
I just pushed a branch mjc/2017-08-28 that has what I believe is a fix for this issue. when testing finishes, I'll merge it to master. Thanks again for the bug report. I had to clean up some older stuff.

**Comment by markcharney** [comment]
pushed. Let me know if this improves things for you. Thanks.

**Comment by OZ1** [comment]
thx

**Comment by markcharney** [comment]
Ok then. I'll close this one.
