### ISSUE TITLE
XED issues XED_REG_EIP instead of XED_REG_RIP in 64bit mode for some XED_OPERAND_AGEN operands

### ISSUE THREAD

**Issue by mcyril** [intelxed/xed#67]
XED issues XED_REG_EIP as a base register for LEA instead of XED_REG_RIP in 64bit mode for XED_OPERAND_AGEN operand. for example (vm: hex-code -> op-code):

1000194ca: 488D3D 8F5A5900 -> lea rdi, 0x1005aef60 (EIP)

vs.

1001b4d36: 488D05 23A23F00 -> lea rax, 0x1005aef60 (RIP)
1001f1cbd: 4C8D2D 9CD23B00 -> lea r13, 0x1005aef60 (RIP)

**Comment by mcyril** [comment]
please ignore/drop this issue: seems it was my local mess of the cached source code (obsoleted branch appeared in debugging session). I'm sorry :(

**Comment by markcharney** [comment]
no problem.
