### ISSUE TITLE
XED build with --knc is broken

### ISSUE THREAD

**Issue by flobernd** [intelxed/xed#78]
Hey there,

it seems like one of the latest changes broke the build with `--knc` switch.
```
[WARNING] isa_set referenced by chip model hierarchy,but not used by any instructions: FAT_NOP
[WARNING] isa_set referenced by chip model hierarchy,but not used by any instructions: PREFETCHW
[WARNING] bad isa_set referenced cpuid file: XED_ISA_SET_CLWB
[ERROR] Found bad isa_sets in cpuid input files.
  File "./pysrc/generator.py", line 6445, in <module>
    main()
  File "./pysrc/generator.py", line 6429, in main
    gen_cpuid_map(agi)
  File "./pysrc/generator.py", line 5848, in gen_cpuid_map
    make_cpuid_mappings(agi, mappings)
  File "./pysrc/generator.py", line 5814, in make_cpuid_mappings
    die("Found bad isa_sets in cpuid input files.")
  File "./pysrc/genutil.py", line 83, in die
    traceback.print_stack()
```
Not sure how to fix this.

**Comment by markcharney** [comment]
You are correct! I'll take a look.

**Comment by markcharney** [comment]
I had disabled AVX512 when the KNC ISA was enabled because several instructions have identical  encodings (in the VEX space) but different names.  The problem here is that the CLWB and CLFLUSHOPT instructions were attached to the SKX chip (which has AVX512). I can omit these when building KNC.

**Comment by flobernd** [comment]
Thanks a lot! This fixes the original issue, but now I get:
```
[MBUILD WARNING] Command execution failed. Waiting for remaining jobs and exiting.
[STATUS] RUNNING: 3    PENDING: 0    COMPLETED: 108   ERRORS: 1   ELAPSED: 2 secs
'utf-8' codec can't decode byte 0x81 in position 172: invalid start byte
```
Im trying to build XED on windows. Got a similar error (but with different position and hex-byte) earlier with the `python ../mfile.py examples` commandline.

**Comment by markcharney** [comment]
unicode.... zounds! wonder where that came from...  are you using python2 or python3? 
Your source is clean?  You didn't happen edit any files?  i could not repro this issue. need more information.

**Comment by flobernd** [comment]
Im using python 3.6 and did not change any files. I even removed the `xed` and `mbuild` directories from my disk and pulled them again (using TortoiseGit in this case).

This did not fix the 'utf-8' error in the first case, but now it "magically" disappeared 😆

**Comment by markcharney** [comment]
> This did not fix the 'utf-8' error in the first case, but now it "magically" disappeared 

So it sounds like it did fix the error? Let me know if you are still experiencing an issue.

**Comment by flobernd** [comment]
> So it sounds like it did fix the error? Let me know if you are still experiencing an issue.
It's working for now. I'll further investigate and open a seperate issue for the error, if it comes back.

Thanks!
