### ISSUE TITLE
typos in datafile

### ISSUE THREAD

**Issue by lyrachord** [intelxed/xed#91]
Seems typos:
xed-reg-tables.txt:551
```
# MOV to CR cannot load CS 
xed_reg_enum_t SEG_MOV()::
```
should be "MOV to SEG"

xed-state-bits.txt:76
```
############################################################3333
f2_prefix              REP=2  # REPNZ, REPNE
f3_prefix              REP=3  # REPZ,  REPNZ
```
3333 typo, because shift key missed
"REPNZ" should be "REPE, REP"

**Comment by markcharney** [comment]
got it. thx. will push when I have some more stuff accumulated.

**Comment by lyrachord** [comment]
Thanks.

Indeed I can request pull operation, but I'm not certain something about xed consideration of design, so an issue here:-)

**Comment by markcharney** [comment]
pushed commit for this today. thx
