### ISSUE TITLE
multiple crashes due to illegal memory reads

### ISSUE THREAD

**Issue by HongxuChen** [intelxed/xed#93]
We found several illegal memory reads bugs as to `xed` decoder with our fuzzing tool [FOT](https://github.com/ntu-sec/fot) (we plan to open source in future). The bug can be replayed with the following compilation options.

```bash
../xed/mfile.py install --cc=clang --cxx=clang++ --extra-flags="-fsanitize=address" --extra-linkflags="-fsanitize=address" --opt=0 --debug --install-dir=$PWD/asan
cd asan/examples/
./mfile.py --cc=clang --cxx=clang++ --extra-flags="-fsanitize=address" --extra-linkflags="-fsanitize=address" --debug --opt=0
cd obj/examples
```

and run

```bash
./xed -i <input_file>
```

clang version is 64bit 4.0.0-1ubuntu1~16.04.2 (tags/RELEASE_400/rc1).

We attach each kind of crashes separately based on the crash site. The attached files are into 2 categories, 

1. `*.input.txt` - input files
2. `*.err.txt` -- stderr output with Address sanitizer

**Comment by HongxuChen** [comment]
crash site: xed-disas-elf.c:535

[w02_000000,sig:11,Flip1:504:78400,src:w00_000000.err.txt](https://github.com/intelxed/xed/files/1588947/w02_000000.sig.11.Flip1.504.78400.src.w00_000000.err.txt)
[w02_000000,sig:11,Flip1:504:78400,src:w00_000000.input.txt](https://github.com/intelxed/xed/files/1588948/w02_000000.sig.11.Flip1.504.78400.src.w00_000000.input.txt)

[w04_000000,sig:11,Flip1:504:78400,src:w02_000001.err.txt](https://github.com/intelxed/xed/files/1588949/w04_000000.sig.11.Flip1.504.78400.src.w02_000001.err.txt)
[w04_000000,sig:11,Flip1:504:78400,src:w02_000001.input.txt](https://github.com/intelxed/xed/files/1588950/w04_000000.sig.11.Flip1.504.78400.src.w02_000001.input.txt)

**Comment by HongxuChen** [comment]
crash site: xed-disas-elf.c:533:28

[w02_000001,sig:11,Flip32:44:9797,src:w00_000000.err.txt](https://github.com/intelxed/xed/files/1588954/w02_000001.sig.11.Flip32.44.9797.src.w00_000000.err.txt)
[w02_000001,sig:11,Flip32:44:9797,src:w00_000000.input.txt](https://github.com/intelxed/xed/files/1588955/w02_000001.sig.11.Flip32.44.9797.src.w00_000000.input.txt)

[w03_000000,sig:11,Flip32:44:9797,src:w04_000000.err.txt](https://github.com/intelxed/xed/files/1588956/w03_000000.sig.11.Flip32.44.9797.src.w04_000000.err.txt)
[w03_000000,sig:11,Flip32:44:9797,src:w04_000000.input.txt](https://github.com/intelxed/xed/files/1588957/w03_000000.sig.11.Flip32.44.9797.src.w04_000000.input.txt)

[w04_000001,sig:11,Flip32:44:9797,src:w02_000001.err.txt](https://github.com/intelxed/xed/files/1588958/w04_000001.sig.11.Flip32.44.9797.src.w02_000001.err.txt)
[w04_000001,sig:11,Flip32:44:9797,src:w02_000001.input.txt](https://github.com/intelxed/xed/files/1588959/w04_000001.sig.11.Flip32.44.9797.src.w02_000001.input.txt)

**Comment by HongxuChen** [comment]
crash site: xed-disas-elf.c:538:21

[w02_000002,sig:11,Flip32:8420:9797,src:w00_000000.err.txt](https://github.com/intelxed/xed/files/1588965/w02_000002.sig.11.Flip32.8420.9797.src.w00_000000.err.txt)
[w02_000002,sig:11,Flip32:8420:9797,src:w00_000000.input.txt](https://github.com/intelxed/xed/files/1588966/w02_000002.sig.11.Flip32.8420.9797.src.w00_000000.input.txt)

**Comment by HongxuChen** [comment]
crash site: xed-examples-util.c:861:13

[w02_000003,sig:11,Flip32:8484:9797,src:w00_000000.err.txt](https://github.com/intelxed/xed/files/1588969/w02_000003.sig.11.Flip32.8484.9797.src.w00_000000.err.txt)
[w02_000003,sig:11,Flip32:8484:9797,src:w00_000000.input.txt](https://github.com/intelxed/xed/files/1588970/w02_000003.sig.11.Flip32.8484.9797.src.w00_000000.input.txt)

[w03_000001,sig:11,Flip32:8484:9797,src:w04_000000.err.txt](https://github.com/intelxed/xed/files/1588971/w03_000001.sig.11.Flip32.8484.9797.src.w04_000000.err.txt)
[w03_000001,sig:11,Flip32:8484:9797,src:w04_000000.input.txt](https://github.com/intelxed/xed/files/1588972/w03_000001.sig.11.Flip32.8484.9797.src.w04_000000.input.txt)

[w04_000002,sig:11,Flip32:8484:9797,src:w02_000001.err.txt](https://github.com/intelxed/xed/files/1588973/w04_000002.sig.11.Flip32.8484.9797.src.w02_000001.err.txt)
[w04_000002,sig:11,Flip32:8484:9797,src:w02_000001.input.txt](https://github.com/intelxed/xed/files/1588974/w04_000002.sig.11.Flip32.8484.9797.src.w02_000001.input.txt)

**Comment by HongxuChen** [comment]
crash site: xed-disas-elf.c:428:43

[w04_000003,sig:11,Flip1:504:78400,src:w02_000003.err.txt](https://github.com/intelxed/xed/files/1588976/w04_000003.sig.11.Flip1.504.78400.src.w02_000003.err.txt)
[w04_000003,sig:11,Flip1:504:78400,src:w02_000003.input.txt](https://github.com/intelxed/xed/files/1588977/w04_000003.sig.11.Flip1.504.78400.src.w02_000003.input.txt)

**Comment by markcharney** [comment]
thx. i will take a look. (more concerned if you could get a crash in libxed rather than the examples though.) btw, this is the 2nd fuzzer to “attack” the code. first one found a lot of stuff, almost all in the examples. one was a case of malformed input not being fully validated and that led to libxed crash.

**Comment by HongxuChen** [comment]
@markcharney Exactly as what you say. TBH, we heard this project recently and we had a try a few hours ago. But since our fuzzing tool still relies on a driver program (our tool aims to be superior to AFL in multiple aspects for research  purpose, but for now it is still targeted on user-space binaries), and since we ourselves have limited experience in XED, we are not able to use libxed in a sensitive way. Therefore finally we followed the practice to fuzz the binary as it is commonly done for binutils, openssl, etc.
We would really appreciate if you can give some hints on using libxed for real world scenarios.

**Comment by HongxuChen** [comment]
crash site: xed-disas-elf.c:534:42

[w02_000000,sig:11,Flip1:504:78400,src:w00_000000.err.txt](https://github.com/intelxed/xed/files/1596062/w02_000000.sig.11.Flip1.504.78400.src.w00_000000.err.txt)
[w02_000000,sig:11,Flip1:504:78400,src:w00_000000.input.txt](https://github.com/intelxed/xed/files/1596063/w02_000000.sig.11.Flip1.504.78400.src.w00_000000.input.txt)

[w04_000003,sig:11,Flip1:504:78400,src:w02_000003.err.txt](https://github.com/intelxed/xed/files/1596064/w04_000003.sig.11.Flip1.504.78400.src.w02_000003.err.txt)
[w04_000003,sig:11,Flip1:504:78400,src:w02_000003.input.txt](https://github.com/intelxed/xed/files/1596065/w04_000003.sig.11.Flip1.504.78400.src.w02_000003.input.txt)

**Comment by HongxuChen** [comment]
crash site: xed-disas-elf.c:427:32

[w04_000003,sig:11,Flip1:504:78400,src:w02_000003.err.txt](https://github.com/intelxed/xed/files/1596067/w04_000003.sig.11.Flip1.504.78400.src.w02_000003.err.txt)
[w04_000003,sig:11,Flip1:504:78400,src:w02_000003.input.txt](https://github.com/intelxed/xed/files/1596068/w04_000003.sig.11.Flip1.504.78400.src.w02_000003.input.txt)

**Comment by HongxuChen** [comment]
crash site: xed-disas-elf.c:476:13

[w02_000004,sig:11,Flip32:8513:1403,src:w01_000436.err.txt](https://github.com/intelxed/xed/files/1596645/w02_000004.sig.11.Flip32.8513.1403.src.w01_000436.err.txt)
[w02_000004,sig:11,Flip32:8513:1403,src:w01_000436.input.txt](https://github.com/intelxed/xed/files/1596646/w02_000004.sig.11.Flip32.8513.1403.src.w01_000436.input.txt)

[w02_000005,sig:11,Flip32:9665:325,src:w01_000436.err.txt](https://github.com/intelxed/xed/files/1596647/w02_000005.sig.11.Flip32.9665.325.src.w01_000436.err.txt)
[w02_000005,sig:11,Flip32:9665:325,src:w01_000436.input.txt](https://github.com/intelxed/xed/files/1596648/w02_000005.sig.11.Flip32.9665.325.src.w01_000436.input.txt)

**Comment by markcharney** [comment]
I have a simple fix for these (checking limit on low end of memory region due to negative offset)

w02_000000.sig.11.Flip1.504.78400.src.w00_000000.input.txt
w02_000001.sig.11.Flip32.44.9797.src.w00_000000.input.txt
w02_000002.sig.11.Flip32.8420.9797.src.w00_000000.input.txt
w03_000000.sig.11.Flip32.44.9797.src.w04_000000.input.txt
w04_000000.sig.11.Flip1.504.78400.src.w02_000001.input.txt
w04_000001.sig.11.Flip32.44.9797.src.w02_000001.input.txt

I'm working on these two next: 
w03_000001.sig.11.Flip32.8484.9797.src.w04_000000.input.txt
w04_000002.sig.11.Flip32.8484.9797.src.w02_000001.input.txt
which seem similar.

**Comment by markcharney** [comment]
got the other two just mentioned also. Now to check the later files yo uploaded...

**Comment by markcharney** [comment]
I believe I addressed all the issues. thanks for finding them & taking the time to file repro cases. Much appreciated.  If you find additional issues, please open a new issue. Thanks!

**Comment by HongxuChen** [comment]
@markcharney Thanks! We are still testing our fuzzing tools against to see whether it has capability to find other potential vulnerabilities and we will follow your advice if we find issues.
BTW, can we request a CVE ID for the issues above?

**Comment by markcharney** [comment]
cve ids are for security vulnerabilities in widely used sw. not appropriate in this case. made me smile though.

**Comment by HongxuChen** [comment]
OK. We were basically following others' CVE practice on GNU Binutils; but it's fine that it is not appropriate.
