### ISSUE TITLE
VCVTUSI2SS with EVEX.W1 in 32 bit mode

### ISSUE THREAD

**Issue by Gumix** [intelxed/xed#95]
Hi!

There are several instructions (like VCVTUSI2SS), for which SDM says: "EVEX.W in non-64 bit is ignored; the instructions behaves as if the W0 version is used", however xed doesn't allow W=1 in 32 bit mode:

>./obj/examples/xed -32 -d 62 f1 86 08 7b 00
>62F186087B00
>ERROR: GENERAL_ERROR Could not decode at offset: 0x0 PC: 0x0: [62F186087B00000000000000000000]

With W=0 everything is fine as expected:

>./obj/examples/xed -32 -d 62 f1 06 08 7b 00
>62F106087B00
>ICLASS: VCVTUSI2SS   CATEGORY: CONVERT   EXTENSION: AVX512EVEX  IFORM: VCVTUSI2SS_XMMf32_XMMf32_MEMu32_AVX512   ISA_SET: AVX512F_SCALAR
>SHORT: vcvtusi2ss xmm0, xmm7, dword ptr [eax]

**Comment by markcharney** [comment]
thanks. I'll fix this soon.

**Comment by markcharney** [comment]
There were a bunch of WIG-in-non64b-mode instr that I had to modify.  The script I used to generate the grammar was not smart enough to handle this case.  (Out of time today... )
