### ISSUE TITLE
read offset errors during 64bit lookup of sh_name

### ISSUE THREAD

**Issue by HongxuChen** [intelxed/xed#99]
When running on a Linux 64 machine, our fuzzing tool generated a series of test cases that we think result from two similar root causes: in `xed-disas-elf.c`, during `process_elf64` and `symbols_elf64`, the actual parameter `offset` of `lookup64` seems to be calculated wrongly.

For `process_elf64`, some test cases cause segfaults with the regular compilation options, others can trigger crashes with help of address sanitizer.

- crash site: xed-disas-elf.c:446
direct segfault
[w01_000001,sig:6,Splice:48:102,src:w00_000000.gdb.txt](https://github.com/intelxed/xed/files/1612291/w01_000001.sig.6.Splice.48.102.src.w00_000000.gdb.txt)
[w01_000001,sig:6,Splice:48:102,src:w00_000000.input.txt](https://github.com/intelxed/xed/files/1612292/w01_000001.sig.6.Splice.48.102.src.w00_000000.input.txt)
crash with asan
[w01_000003,sig:6,Flip1:496:53984,src:w01_000822.err.txt](https://github.com/intelxed/xed/files/1612316/w01_000003.sig.6.Flip1.496.53984.src.w01_000822.err.txt)
[w01_000003,sig:6,Flip1:496:53984,src:w01_000822.input.txt](https://github.com/intelxed/xed/files/1612317/w01_000003.sig.6.Flip1.496.53984.src.w01_000822.input.txt)

 
For `symbols_elf64`, the crash we found can be triggered with address sanitizer.
- crash site: xed-disas-elf.c:557:53
[w02_000000,sig:6,Flip1:496:37632,src:w01_000000.err.txt](https://github.com/intelxed/xed/files/1612323/w02_000000.sig.6.Flip1.496.37632.src.w01_000000.err.txt)
[w02_000000,sig:6,Flip1:496:37632,src:w01_000000.input.txt](https://github.com/intelxed/xed/files/1612324/w02_000000.sig.6.Flip1.496.37632.src.w01_000000.input.txt)

We are not aware whether 32bit elf disassembly is affected since our fuzzer hasn't covered the corresponding functions yet.

**Comment by HongxuChen** [comment]
32 elf seems affected.

with asan, inside `symbols_elf32`
crash site: xed-disas-elf.c:661:53

[w01_000000,sig:6,Flip1:400:8672,src:w00_000003.err.txt](https://github.com/intelxed/xed/files/1612387/w01_000000.sig.6.Flip1.400.8672.src.w00_000003.err.txt)
[w01_000000,sig:6,Flip1:400:8672,src:w00_000003.input.txt](https://github.com/intelxed/xed/files/1612388/w01_000000.sig.6.Flip1.400.8672.src.w00_000003.input.txt)

**Comment by markcharney** [comment]
Looks like the latest round of examples are supplying a bogus large section number for strings. I put in a guard against referring to the memory indicated (and unified some other checks). These 4 are no longer crashing.

**Comment by markcharney** [comment]
will push with my next round of updates (got a few queued up)
